export const songRequestsMock = [
  {
    id: 1,
    songName: "Song 1",
    spotifyLink: "asd",
    played: true,
    dateRequested: 1657737349, 
  },
  {
    id: 2,
    songName: "Test",
    spotifyLink: "asd",
    played: false,
    dateRequested: 1657737321, 
  },
  {
    id: 3,
    songName: "Test",
    spotifyLink: "asd",
    played: true,
    dateRequested: 1657737321, 
  },
  {
    id: 4,
    songName: "Test",
    spotifyLink: "asd",
    played: true,
    dateRequested: 1657737321, 
  },
  {
    id: 5,
    songName: "Test",
    spotifyLink: "asd",
    played: false,
    dateRequested: 1657737321, 
  },
  {
    id: 6,
    songName: "Test",
    spotifyLink: "asd",
    played: true,
    dateRequested: 1657737321, 
  },
  {
    id: 7,
    songName: "Test",
    spotifyLink: "asd",
    played: true,
    dateRequested: 1657737321, 
  },
  {
    id: 8,
    songName: "Test",
    spotifyLink: "asd",
    played: true,
    dateRequested: 1657737321, 
  },
  {
    id: 9,
    songName: "Test",
    spotifyLink: "asd",
    played: true,
    dateRequested: 1657737321, 
  },
  {
    id: 10,
    songName: "Test",
    spotifyLink: "asd",
    played: false,
    dateRequested: 1657737321, 
  },
  {
    id: 11,
    songName: "Test",
    spotifyLink: "asd",
    played: true,
    dateRequested: 1657737321, 
  },
  {
    id: 12,
    songName: "Test",
    spotifyLink: "asd",
    played: true,
    dateRequested: 1657737321, 
  },
  {
    id: 13,
    songName: "Test",
    spotifyLink: "asd",
    played: true,
    dateRequested: 1657737321, 
  },
  {
    id: 14,
    songName: "Test",
    spotifyLink: "asd",
    played: false,
    dateRequested: 1657737321, 
  },
  {
    id: 15,
    songName: "Test",
    spotifyLink: "asd",
    played: true,
    dateRequested: 1657737321, 
  },
]
